# Generated by Django 4.1 on 2022-08-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('words_per_minute', models.IntegerField()),
                ('characters_per_minute', models.IntegerField()),
                ('accuracy', models.IntegerField()),
            ],
        ),
    ]
